# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: test

  # tavern
  test:
    cmds:
      - rye run pytest {{.CLI_ARGS}}

  # rye
  rye-help:
    cmds:
      - rye --help

  version:
    cmds:
      - rye run python --version
      - rye --version
